### ISSUE TITLE
Error compiling with --all-features

### ISSUE THREAD

**Issue by mbridon** [divviup/divviup-api#1417]
I tried to compile divviup-api with `--all-features`:

```
$ cargo build --release --all-features
[... snip compilation ...]
error[E0599]: no method named `provider` found for struct `opentelemetry_sdk::trace::TracerProvider` in the current scope
  --> src/telemetry.rs:52:14
   |
46 | /         opentelemetry_otlp::new_pipeline()
47 | |             .tracing()
48 | |             .with_trace_config(opentelemetry_sdk::trace::Config::default().with_resource(resource))
49 | |             .with_exporter(opentelemetry_otlp::new_exporter().tonic())
50 | |             .install_batch(opentelemetry_sdk::runtime::Tokio)
51 | |             .unwrap()
52 | |             .provider()
   | |             -^^^^^^^^ method not found in `TracerProvider`
   | |_____________|
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `divviup-api` (lib) due to 1 previous error
```

I'm too much of a Rust noob to understand or provide a patch. :sweat_smile:

**Comment by divergentdave** [comment]
Thanks for the report! Looks like this has been broken since #1205. I filed PR #1430 to fix this.
